card_image: ''
created_at: 2025-04-09 15:54:18.021000
creator_id: unknown
deployment:
  last_deployed: null
  type: null
  url: ''
description: AWS Amplify React+Vite Starter Template
domain: ''
features:
- ''
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: https://github.com/memextech/amplify-vite-react-template
hero_image: https://raw.githubusercontent.com/memextech/amplify-vite-react-template/main/public/images/hero-image.png
icon: ''
is_published: true
pills:
- icon: Rocket
  label: Setup & Deployment
  prompt: Guide me through the setup and deployment
project_id: 7zV87U6a4LWU9yH7bFzF
published_at: 2025-04-09 16:00:31.226000
requirements:
- description: ''
  type: ''
slug: ''
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: AWS Amplify React+Vite Starter Template
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-04-09 16:14:29.847000
